version: '3'

services:
  server-web:
    command: bash -c "cd /app
      && cp -a /save/vendor .
      && cp -a /save/var .
      && symfony server:stop
      && symfony server:start"
    volumes:
      - .:/app
    ports:
      - "8000:8000"

###> doctrine/doctrine-bundle ###
###< doctrine/doctrine-bundle ###