version: '3'

services:
  server-web:
    command: bash -c "cd /app
      && symfony server:stop
      && composer update
      && symfony console importmap:install
      && symfony console doctrine:migrations:migrate
      && symfony console tailwind:build
      && symfony server:start"
    volumes:
      - .:/app
      - /app/var
      - /app/vendor
    ports:
      - "8000:8000"

###> doctrine/doctrine-bundle ###
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    container_name: mailer-terminologio
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
###< symfony/mailer ###