version: '3'

services:
  server-web:
    command: bash -c "cd /app
      && symfony server:stop
      && symfony server:start"
    volumes:
      - .:/app
      - /app/var
      - /app/vendor
    ports:
      - "8000:8000"

###> doctrine/doctrine-bundle ###
###< doctrine/doctrine-bundle ###